# Generated by Django 5.2.3 on 2025-06-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='text',
            field=models.CharField(default='Sem título', max_length=200),
        ),
    ]
